language: node_js
node_js:
  - lts/*
script:
  - yarn build:elementui-docs
  - yarn build:vue-demo
  - yarn build:vuese-docs
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: dist
  github-token: $GITHUB_TOKEN
  on:
    branch: master